services:
  db:
    image: postgres
    container_name: movie-recommender-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgadmin4
      POSTGRES_DB: movie-recommender
    ports:
      - "5432:5432"
    networks:
      - movie-network
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    depends_on:
      db:
        condition: service_healthy
    container_name: movie-recommender-api
    environment:
      DATABASE_URL: "postgresql+psycopg://postgres:pgadmin4@db:5432/movie-recommender"
    ports:
      - "8000:8000"
    networks:
      - movie-network

networks:
  movie-network:
    driver: bridge

volumes:
  postgres_data: